name: Build V8 for Windows x64

on:
  workflow_dispatch:

jobs:
  build-v8:
    runs-on: windows-latest

    env:
      V8_VERSION: '12.8'
      PLATFORM: 'x64'
      LIBS: 'shared'

    steps:
      - name: Checkout v8-nuget
        uses: actions/checkout@v4
        with:
          repository: pmed/v8-nuget

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Git LFS
        run: |
          choco install git-lfs -y
          git lfs install

      - name: Set VCINSTALLDIR from VSINSTALLDIR
        run: |
          echo "VCINSTALLDIR=$env:VSINSTALLDIR" >> $env:GITHUB_ENV

      - name: Build V8
        run: |
          python build.py --version=${{ env.V8_VERSION }} --platform=${{ env.PLATFORM }} --libs=${{ env.LIBS }}

      - name: Upload V8 binaries
        uses: actions/upload-artifact@v4
        with:
          name: v8-binaries
          path: |
            out/v8-${{ env.V8_VERSION }}-${{ env.PLATFORM }}-release-${{ env.LIBS }}/v8.dll
            out/v8-${{ env.V8_VERSION }}-${{ env.PLATFORM }}-release-${{ env.LIBS }}/v8.lib
            out/v8-${{ env.V8_VERSION }}-${{ env.PLATFORM }}-release-${{ env.LIBS }}/include/
